### ISSUE TITLE
Self-closing tags

### ISSUE THREAD

**Issue by cshaa** [OscarGodson/HTML6#8]
I think HTML6 should use more of XML's self-closing tags - eg. `<script src="s.js" />` would be great. Of course this is not the best example because it's a file import - can be done using `<html:include />` or something like that. But I think you understand me. Older HTML versions had single tags and double tags but there was no way to recognize them.

**Comment by OscarGodson** [comment]
I think making it optional to use either would be cool. If you send a PR with an explanation and sample or something I'll merge it in :)

**Comment by cshaa** [comment]
Do you think that CSS can be used to explain document restrictions? We need something like DTD but no one knows it nowadays so I think we shouldn't use it.
Example of my idea - CDS, the cascading description sheet:

``` css
@namespace {
 html {
  childs: namespaced element("head", "body");
  /* html:html can contain html:head and html:body */
 }
 head {
  childs: both element("meta", "title");
  display: none;
 }
 body {
  childs: both element("anchor", "link", "media");
 }

 anchor, link {
  text-decoration: underline;
  cursor: pointer;
  color: #00f;
 }
}
```
